export type CurriculumDay = {
  name: string; question: string; intro: string; topics: string[]; outcomes: string[];
  revenue?: string[];
};
export type Curriculum = { promise: string; preparation: string[]; days: CurriculumDay[] };

// Customer-facing curriculum from the finalized consultation brief.
// Internal team notes are intentionally excluded.
export const consultationCurriculum: Curriculum[] = [
  {
    promise: "A clear creator identity, content direction, an idea-generation system and a 15-day content roadmap built around you.",
    preparation: ["Your background, goals, interests, skills and personality", "Your current content, audience and social media links, if you have them", "Creators who inspire you and any existing performance data"],
    days: [
      { name: "Discover", question: "Who are you as a creator?", intro: "We use your Creator DNA assessment to understand your strengths, interests, audience and positioning.", topics: ["The goal you want to achieve as a creator", "What interests you and what you want to showcase", "The creator identity you want to build", "The time, effort and commitment you can invest", "Your long-term plans and why you want to create", "How content creation fits into your life and future", "Your motivations and what attracts you to creating", "The audience you want to reach and the value you can give them"], outcomes: ["A clearer creator identity and positioning", "A realistic direction based on your goals, strengths and available time"] },
      { name: "Design", question: "What should you actually make?", intro: "We turn your Creator DNA into a content system you can use when planning your next upload.", topics: ["Content pillars: the recurring categories and topics your content can revolve around", "Formats suited to you and worth testing", "Repeatable concepts that can become recurring series", "Idea-generation frameworks for when you run out of ideas", "Topics worth exploring and topics to avoid", "Your content sweet spot: what interests both you and your audience"], outcomes: ["Your content pillars, formats and recurring concepts", "A personal idea-generation system and clear criteria for choosing topics"] },
      { name: "Build", question: "How do you turn this into an actual content journey?", intro: "We bring the first two calls together in an execution plan for your first 15 days.", topics: ["An initial posting strategy", "How to test and analyse an idea", "A plan for experimenting with different content concepts", "Which ideas to prioritise first", "The key signals to measure for each type of content", "What to do after the first 15 days to build your creator brand"], outcomes: ["15 personalised content ideas developed around your Creator DNA, audience and direction", "A 15-day roadmap covering what to create, test and publish", "Your personal Creator Blueprint"] },
    ],
  },
  {
    promise: "A personal system for creating, packaging and testing content for stronger reach, retention and audience response.",
    preparation: ["Your social media links and relevant analytics", "Your best-performing and worst-performing content", "The content you feel was your best work, regardless of views", "Your current content strategy, biggest growth problems and goals", "Creators you consider competition or inspiration"],
    days: [
      { name: "Analyse the data", question: "Why is your content performing the way it is?", intro: "We review the content and data you share before the first call, then diagnose the decisions affecting performance.", topics: ["Your strongest and weakest content and the patterns behind it", "Audience response, retention and where viewers drop off", "Hooks, packaging, storytelling and content formats", "Repeatable winning patterns and what is holding you back"], outcomes: ["Your Content Performance Diagnosis: what is working and what is not", "The biggest opportunities to improve reach, retention and engagement", "What to stop doing, what to strengthen and what to start testing"] },
      { name: "Hook & retention", question: "How do you make people stop and keep watching?", intro: "We focus on getting attention and keeping it, with examples from your own short-form content.", topics: ["Hook strategy and the first frame", "Curiosity and open loops", "Pacing, information delivery and story progression", "Payoffs and retention patterns", "Where viewers lose interest and how to improve weak openings"], outcomes: ["Your personalised hook and retention frameworks", "Improved versions of your existing hooks", "A repeatable structure for more engaging videos"] },
      { name: "Content & storytelling", question: "How do you turn a good idea into a great video?", intro: "We work through the structure that takes an idea from promising to watchable.", topics: ["Story and content structure", "Escalation, conflict and payoffs", "Pacing and information density", "Emotional engagement and personality", "Repeatable video structures and a more distinctive creator voice"], outcomes: ["Your personalised storytelling framework", "Content structures you can adapt across videos", "Improved structures for upcoming videos", "A repeatable process for developing ideas into stronger content"] },
      { name: "Packaging & optimisation", question: "How do you make people choose your content?", intro: "We study how your content is presented before the audience starts watching.", topics: ["Titles, thumbnails and first frames", "Captions, hooks and calls to action", "Topics, angles and content positioning", "Platform-specific packaging and how your content compares with alternatives"], outcomes: ["Your personal packaging framework", "Repeatable hook and title approaches", "Thumbnail and first-frame principles", "A pre-publishing evaluation system for finding weak points before upload"] },
      { name: "Optimise & scale", question: "How do you make performance repeatable?", intro: "We build a way to learn from every upload and decide what to try next.", topics: ["A performance analysis system and testing framework", "Content experimentation and winning-format identification", "An iteration strategy and the metrics to track", "How to compare content and decide what to double down on", "What to stop and your next content priorities"], outcomes: ["Your Content Performance System", "A content testing and performance tracking framework", "Priority formats based on your data", "Specific next experiments and a personalised growth roadmap"] },
    ],
  },
  {
    promise: "The people, systems, workflows and business strategy needed to grow a creator operation that does not depend on you for every decision.",
    preparation: ["Social media links, current revenue streams, monthly revenue and expenses", "Team structure, roles and responsibilities", "Your production workflow and existing systems or SOPs", "Your workload, biggest bottlenecks and challenges with scaling", "Business goals and your long-term vision"],
    days: [
      { name: "Audit", question: "Where does your creator business stand today?", intro: "We look at your operation as a whole to find what is helping it grow and what is limiting it.", topics: ["Business structure, revenue and expenses", "Content operations, team and workload", "Time allocation, bottlenecks and dependencies", "Current systems and growth opportunities"], outcomes: ["Your Creator Business Diagnosis", "The biggest bottlenecks and growth opportunities", "A founder dependency analysis", "A priority roadmap for what to address first"] },
      { name: "Organise", question: "How should your creator business be structured?", intro: "We design a team structure with clear ownership, communication and decisions.", topics: ["Team structure and required positions", "Roles, responsibilities, delegation and ownership", "Decision-making and communication structure", "Your responsibilities as the founder"], outcomes: ["Your creator business org chart", "A role and responsibility map", "A delegation plan", "Hiring priorities based on your current needs"] },
      { name: "Hire", question: "How do you build the right team?", intro: "We build a hiring strategy around what your operation actually needs.", topics: ["Who to hire and when", "Employee versus freelancer", "Role requirements and the skills to look for", "Hiring process, trial periods and evaluation criteria", "Performance expectations"], outcomes: ["A hiring roadmap explaining the order and purpose of each role", "Role requirements", "A candidate evaluation framework", "A trial and performance framework for new team members"] },
      { name: "Systemise", question: "How can the business work without everything going through you?", intro: "We turn repeated processes into workflows the team can follow.", topics: ["Idea generation, scripting and shooting", "Editing, thumbnails and publishing", "Content review and analytics", "Team communication and project management"], outcomes: ["Your Creator Operating System", "A core workflow from idea to publication", "SOP priorities: what to document first", "A delegation system for moving work between you and the team"] },
      { name: "Handle", question: "How do you lead and work with a team?", intro: "We cover the practical decisions behind communication, feedback, trust and accountability.", topics: ["Clear communication, expectations and what to delegate", "Giving effective feedback", "Handling mistakes and conflicts", "Accountability and trust without losing authority", "Avoiding micromanagement", "Motivation and healthy boundaries"], outcomes: ["Your team management framework", "Practical team dos and don'ts", "A communication framework for expectations, feedback and decisions", "An accountability system that reduces the need to chase work"] },
      { name: "Profit", question: "How do you make the operation profitable?", intro: "We build a monetisation strategy that accounts for operating costs and leaves room for growth.", topics: ["Revenue streams and monetisation opportunities that fit your audience and brand", "Team and production cost recovery", "Brand deals as part of the revenue mix", "Products and services built around your expertise", "Revenue diversification", "Profit margins and when to reinvest in people, content and growth"], outcomes: ["Your creator business model", "A monetisation roadmap", "A team cost recovery plan", "A profit and reinvestment strategy", "A revenue expansion plan and business priorities"] },
      { name: "Future-proof", question: "How do you build a business that can keep growing?", intro: "We work on long-term stability, profit and independence from a single platform, person or income stream. You also get a private look at the real economics of videos from my own channels.", topics: ["Creator economics: what selected videos actually generated", "Revenue, production costs, team costs and unit economics", "Revenue and platform diversification", "Building your brand and intellectual property", "Founder independence and risk management", "Long-term expansion and how your founder role should evolve"], revenue: ["Selected videos, their views and actual revenue", "How different formats and types of content monetise", "How audience and platform affect earnings", "Why high views do not automatically mean high profit", "How production and team costs change the result", "How to think about content as a business asset"], outcomes: ["Your Creator Economics Framework", "A future-proofing strategy", "A diversification roadmap", "Long-term expansion opportunities", "Your Founder Evolution Plan", "A 12–24 month strategic vision"] },
    ],
  },
];
