import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { milestones } from "../../lib/content";

export const metadata: Metadata = { title: "About", description: "The story behind Rakshit Jain: from a young creator to strategist, operator and founder." };

export default function About() {
  return <><section className="page-hero wrap split-hero"><div><p className="eyebrow">About / Rakshit Jain</p><h1 className="display-title">Built early.<br/><em>Still building.</em></h1><p className="lead">I&apos;m Rakshit Jain. I&apos;ve spent much of my childhood learning how content works, then learning what it takes to make a creator business work.</p><div className="button-row"><Link className="pill-button" href="/work">See the work ↗</Link><Link className="text-link" href="/consultations">Work with me ↗</Link></div></div><div className="portrait portrait-about"><span>RAKSHIT JAIN / NEW DELHI</span></div></section>
    <section className="section section-dark"><div className="wrap narrative"><p className="eyebrow">The story</p><h2 className="display-title">Curiosity became <em>an obsession.</em></h2><div className="narrative-columns"><p>I began working on projects around eight and studying content creation seriously around ten. I watched creators, studied what made videos work and kept experimenting. In March 2022, I started publishing on YouTube, initially through Minecraft and gaming.</p><p>There were failed ideas, videos that went nowhere and stretches where growth stopped. Those moments taught me to ask better questions: what went wrong, why did it happen, and what should I test next? By October 2025, the channel reached one million subscribers, 11 months after crossing 100K.</p><p>As the audience grew, the challenge changed. I expanded into IRL, gaming and technology, worked across multiple channels and built a 20–25 person creative operation. I had to learn hiring, delegation, workflows, quality control, costs and how to think beyond a single video.</p><p>Experience in e-commerce added another layer: product selection, marketing, customer acquisition, paid advertising, revenue and profitability. That is why my work with creators now spans content direction, performance and the business behind it.</p></div></div></section>
    <section className="about-film"><div><Image src="/images/raksh-travel.webp" alt="Rakshit exploring a motorsport venue" width={700} height={900}/><span>KEEP EXPLORING</span></div><div><Image src="/images/raksh-hero.webp" alt="Rakshit at an immersive venue" width={700} height={900}/><span>KEEP MAKING</span></div><div><Image src="/images/raksh-world.webp" alt="Rakshit during a trip to SeaWorld" width={700} height={900}/><span>KEEP BUILDING</span></div></section>
    <section className="section wrap"><div className="section-heading"><div><p className="eyebrow">Milestones</p><h2 className="display-title">The long way <em>forward.</em></h2></div><p>Growth came from testing, studying audience response and changing the work along the way.</p></div><div className="timeline">{milestones.map((m) => <div className="timeline-row" key={m.date}><span>{m.date}</span><div><h3>{m.title}</h3><p>{m.body}</p></div><b>↗</b></div>)}</div></section>
    <section className="section section-dark"><div className="wrap philosophy"><div className="portrait portrait-stage"/><div><p className="eyebrow">What I believe</p><h2>Consistency gives you chances to improve. <em>Deliberate improvement</em> turns those chances into growth.</h2><p>Idea → Hook → Retention → Storytelling → Packaging → Audience response → Analysis → Iteration. The work is to understand why something works, instead of copying what went viral.</p><Link href="/consultations" className="underlined-link">See how I work with creators ↗</Link></div></div></section>
    <section className="section wrap"><p className="eyebrow">The shift</p><div className="stage-grid">{[{t:"Creator",d:"Making videos, developing ideas and understanding audiences."},{t:"Strategist",d:"Studying hooks, retention, formats and audience behaviour."},{t:"Operator",d:"Building teams, systems, workflows and quality control."},{t:"Founder",d:"Thinking about profitability, revenue and what lasts beyond a single platform."}].map((s,i)=><article key={s.t}><span>0{i+1}</span><h3>{s.t}</h3><p>{s.d}</p></article>)}</div></section>
    <section className="recognition section section-dark"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Recognition along the way</p><h2 className="display-title">The milestones<br/><em>behind the momentum.</em></h2></div><p>Creator milestones and invitations shared by Rakshit. The work behind them started long before the awards arrived.</p></div><div className="recognition__grid">{[{n:"100K",title:"YouTube Silver Creator Award",text:"A marker of the first major audience milestone."},{n:"1M",title:"YouTube Gold Creator Award",text:"Reached in October 2025, eleven months after 100K."},{n:"03",title:"YouTube creator events",text:"Invited to three official YouTube events as a creator."},{n:"01",title:"Samsung creator partnership",text:"Creator recognition and a brand partnership."}].map((item)=><article key={item.title}><span>{item.n}</span><div><h3>{item.title}</h3><p>{item.text}</p></div><b>↗</b></article>)}</div><p className="recognition__note">Also recognized by S8UL Esports through an Instagram Reel, as shared by Rakshit.</p></div></section>
  </>;
}
