import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import VideoEmbed from "../../components/VideoEmbed";
import { longVideos } from "../../lib/videos";

export const metadata: Metadata = { title: "Work & Proof", description: "RakshXD case studies, high-performing content and first-party analytics proof." };

const contentResults = [
  { value: "19M+", title: "Most-viewed YouTube Short", kind: "Audience insight + hook" },
  { value: "16M", title: "Personal storytelling Short", kind: "Storytelling at scale" },
  { value: "10M", title: "Creative concept Short", kind: "Format experimentation" },
  { value: "9M", title: "Hook-driven Short", kind: "Opening that earns attention" },
  { value: "3M / 10 days", title: "Creative + hook Short", kind: "Fast audience response" },
  { value: "3M+", title: "Instagram Reel", kind: "Cross-platform hook" },
  { value: "2.8M", title: "Instagram Reel", kind: "Hook-first content" },
  { value: "1M", title: "Instagram Reel", kind: "Creative concept" },
];

export default function Work() {
  return <><section className="page-hero work-hero wrap"><div className="work-hero__copy"><p className="eyebrow">Work / Results / Process</p><h1 className="display-title">The work behind<br/><em>the numbers.</em></h1><p className="lead narrow">From a channel built from scratch to repeat million-view pieces across YouTube and Instagram, these are examples of the decisions behind the numbers.</p><Link href="#work-case-01" className="underlined-link">Explore the case studies ↓</Link></div><div className="work-hero__film" aria-hidden="true"><div className="work-hero__film-card work-hero__film-card--one"><Image unoptimized src="https://i.ytimg.com/vi/FQaeje7tR4Q/hqdefault.jpg" alt="" width={480} height={270}/><span>THE IDEA</span></div><div className="work-hero__film-card work-hero__film-card--two"><Image src="/images/instagram-3m.webp" alt="" width={400} height={600}/><span>THE RESPONSE</span></div><div className="work-hero__film-note"><strong>01 / 03</strong><span>FROM HOOK TO IMPACT</span></div></div></section>
    <section className="metric-band"><div className="wrap metric-grid"><div><strong>1.5M+</strong><span>YouTube subscribers</span></div><div><strong>350M</strong><span>total views reported by Raksh</span></div><div><strong>100K → 1M</strong><span>in 11 months</span></div><div><strong>20–25</strong><span>person operation</span></div></div></section>
    <nav className="work-case-nav" aria-label="Work page sections"><div className="wrap"><span>EXPLORE THE WORK</span><a href="#work-case-01">01 / Growth</a><a href="#work-case-02">02 / A 19M idea</a><a href="#work-longform">03 / Long form</a><a href="#work-proof">04 / Proof</a><a href="#work-case-03">05 / Operation</a></div></nav>
    <section className="work-photo-story section"><div className="wrap"><p className="eyebrow">The person / The process / The proof</p><div className="work-photo-story__grid"><div><Image src="/images/raksh-stage.webp" alt="Raksh at a creator event" width={950} height={1100}/><span>BUILDING IN PUBLIC</span></div><div><Image src="/images/raksh-city.webp" alt="Raksh overlooking the city" width={750} height={900}/><span>THINKING LONG TERM</span></div><p>Each result started as a creative decision: an audience question, an opening frame, a story worth staying for. Then came the part most people don&apos;t see: study the response and make the next one sharper.</p></div></div></section>
    <section className="section wrap" id="work-case-01"><div className="section-heading"><div><p className="eyebrow">Case study / 01</p><h2 className="display-title">100K to 1M.<br/><em>Eleven months.</em></h2></div><p>November 2024 to October 2025. A growth phase built on testing ideas, hooks, storytelling and formats, then using audience response to improve the next piece.</p></div><div className="case-panel"><div><h3>Strategy and iteration, not repetition.</h3><p>Raksh personally handled content strategy, idea selection, experiments, hooks, storytelling and performance analysis. Instead of relying on the format that first worked, the channel kept testing new approaches and learning from the response.</p><p className="fineprint">Channel started in March 2022. Subscriber milestone dates and figures are supplied by Raksh.</p><a className="underlined-link" href="https://www.youtube.com/@RakshXD" target="_blank" rel="noreferrer">Visit the channel ↗</a></div><div className="case-number">1M<span>October 2025</span></div></div><div className="work-proofnote"><span>YOUTUBE STUDIO / SOURCE PERIOD</span><strong>01 Oct 2024 — 01 Oct 2025</strong><a href="https://drive.google.com/drive/folders/1Qd2MSGyrdPK_A-4rKDFRRbNgsVJpUjJ0?usp=sharing" target="_blank" rel="noreferrer">Open supplied analytics ↗</a></div></section>
    <section className="section section-dark" id="work-case-02"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Case study / 02</p><h2 className="display-title">A simple question.<br/><em>19M+ views.</em></h2></div><p>Could a game run on the cheapest laptop? The question reflected a real constraint for many Indian gamers and made the outcome worth watching.</p></div><div className="feature-layout"><VideoEmbed id="aIoVDZAW85w" title="Can this game run on the cheapest laptop?" label="19M+ views · YouTube Short"/><div className="feature-story"><h3>Start with the audience&apos;s reality.</h3><p>The concept paired a relatable low-budget gaming problem with an immediate curiosity gap. Raksh developed the idea, opening hook and execution, then studied how people responded.</p><ul className="arrow-list"><li>Clear audience pain point</li><li>Simple, instantly understood premise</li><li>Multiple questions that keep viewers watching</li></ul><p>The subject was the game. The hook was the audience&apos;s situation.</p></div></div></div></section>
    <section className="work-process section"><div className="wrap work-process__layout"><div className="work-process__story"><p className="eyebrow">The craft behind the clip</p><h2 className="display-title">Build curiosity.<br/><em>Earn the payoff.</em></h2><p>One upload is the visible part. The real work happens in the choices before and after it: picking a question people already care about, packaging it clearly, then reading what the audience actually did.</p><Image src="/images/raksh-about.webp" alt="Raksh at an immersive venue" width={700} height={850}/></div><div className="work-process__steps">{[{n:"01",title:"Find the question",text:"Start with a real audience tension, not a format in search of an idea."},{n:"02",title:"Shape the first frame",text:"Make the promise immediate, visual and easy to understand."},{n:"03",title:"Deliver the story",text:"Give each beat a reason to exist so the audience stays for the answer."},{n:"04",title:"Read the response",text:"Study what held attention, then sharpen the next experiment."}].map((step)=><div className="work-process__step" key={step.n}><span>{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p></div><b>↗</b></div>)}</div></div></section>
    <section className="work-longform section section-dark" id="work-longform"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">Beyond the short</p><h2 className="display-title">Stories built<br/><em>to stay with.</em></h2></div><p>Long-form uploads make the creative decisions visible: the setup, the testing, the reveal and the personality that connects it all.</p></div><div className="work-longform__grid">{longVideos.slice(0,3).map((video,index)=><a className="work-longform__card" key={video.id} href={`https://www.youtube.com/watch?v=${video.id}`} target="_blank" rel="noreferrer"><div className="work-longform__image"><Image unoptimized src={`https://i.ytimg.com/vi/${video.id}/hqdefault.jpg`} alt="" width={480} height={270}/><span>WATCH FILM ↗</span></div><div className="work-longform__meta"><small>RAKSHXD / 0{index+1}</small><h3>{video.title}</h3></div></a>)}</div></div></section>
    <section className="section wrap"><div className="section-heading"><div><p className="eyebrow">More than one viral moment</p><h2 className="display-title">Different skills.<br/><em>Repeated results.</em></h2></div><p>These results span storytelling, concepts and platform-native hooks. Figures are supplied by Raksh; links for these specific posts will be added when available.</p></div><div className="result-grid">{contentResults.map((r,index)=><article className={index===0?"result-grid__featured":""} key={r.value + r.title}>{index===0&&<Image className="result-grid__image" unoptimized src="https://i.ytimg.com/vi/aIoVDZAW85w/hqdefault.jpg" alt="" width={480} height={270}/>}<span className="eyebrow">{r.kind}</span><strong>{r.value}</strong><h3>{r.title}</h3>{index===0&&<a href="https://www.youtube.com/shorts/aIoVDZAW85w" target="_blank" rel="noreferrer">Watch the Short ↗</a>}</article>)}</div></section>
    <section className="section section-dark" id="work-proof"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">First-party analytics</p><h2 className="display-title">Look beneath<br/><em>the view count.</em></h2></div><p>These Instagram screenshots show reach, engagement and retention from Raksh&apos;s own account. They are proof of past content performance, not a promise of client results.</p></div><div className="proof-grid"><figure><Image width={600} height={900} src="/images/instagram-3m.webp" alt="Instagram Reel insights showing over 3 million views"/><figcaption>3M+ Reel · overview</figcaption></figure><figure><Image width={600} height={900} src="/images/instagram-1m.webp" alt="Instagram Reel insights showing over 1 million views"/><figcaption>1M+ Reel · overview</figcaption></figure><figure><Image width={600} height={900} src="/images/instagram-retention.webp" alt="Instagram Reel retention and engagement analytics"/><figcaption>Retention and engagement</figcaption></figure></div><a className="underlined-link" href="https://drive.google.com/drive/folders/1Qd2MSGyrdPK_A-4rKDFRRbNgsVJpUjJ0?usp=sharing" target="_blank" rel="noreferrer">View the supplied proof folder ↗</a></div></section>
    <section className="section wrap" id="work-case-03"><div className="section-heading"><div><p className="eyebrow">Case study / 03</p><h2 className="display-title">From creator<br/><em>to operation.</em></h2></div><p>A 20–25 person creative team across editing, thumbnails, research, production and operations.</p></div><div className="case-panel"><div><h3>Scale needs a system.</h3><p>As RakshXD expanded into multiple channels, Raksh worked on hiring, delegating, creative workflows, quality standards, production costs and strategic decisions. The challenge changed from making more content himself to building an operation that could keep producing well.</p><p>Channels in the wider operation include roboraksh, AlsoRaksh, shaktinaam and moreofraksh.</p><Link href="/consultations" className="underlined-link">Explore the founder module ↗</Link></div><div className="case-number">20–25<span>creative operation</span></div></div></section>
    <section className="work-lastword"><div className="wrap"><span>THE NEXT STORY IS STILL OPEN</span><p>Good work starts with a question worth asking.</p><Link href="/contact">Let&apos;s talk about yours <b>↗</b></Link></div></section>
  </>;
}
