import Image from "next/image";
import Link from "next/link";
import VideoEmbed from "../components/VideoEmbed";
import VideoMarquee from "../components/VideoMarquee";
import { brandVideos, faqs, modules } from "../lib/content";

const journey = [
  { number: "01", phase: "2022 / THE START", title: "Make the first thing.", text: "Gaming and Minecraft became the place to test ideas, learn by doing, and understand what people actually watch.", list: ["Started Raksh Jain on YouTube", "Learned through real uploads", "Built a repeatable creative instinct"], metric: "START", metricLabel: "IT ALL STARTED HERE" },
  { number: "02", phase: "2024–25 / THE MOMENTUM", title: "Find the connection.", text: "One breakthrough led to a sharper process. The channel went from 100K to 1M subscribers in eleven months.", list: ["100K in November 2024", "1M in October 2025", "Multiple million-view ideas"], metric: "1M+", metricLabel: "A SHARPER PROCESS" },
  { number: "03", phase: "NOW / THE OPERATION", title: "Build beyond the channel.", text: "Today the work spans platforms, partnerships, and a 20–25 person operation built to make consistently better content.", list: ["Broader gaming, IRL and tech", "A creative team and systems", "Creator strategy consultations"], metric: "20–25", metricLabel: "A BIGGER CANVAS" },
];

export default function Home() {
  return <>
    <section className="reference-hero reference-hero--raksh" aria-labelledby="hero-title" style={{position: "relative"}}>
      <div style={{position: "absolute", inset: 0, zIndex: -3}}>
        <Image src="/images/raksh-cinematic-bg.png" alt="" fill style={{objectFit: "cover", objectPosition: "center"}} priority />
        <div style={{position: "absolute", inset: 0, background: "radial-gradient(ellipse at center, transparent 30%, rgba(3, 7, 12, 0.5) 100%)", mixBlendMode: "multiply", zIndex: 1}}></div>
      </div>
      <div className="reference-hero__portrait" data-parallax="0.025" style={{zIndex: -2, mixBlendMode: "lighten", WebkitMaskImage: "linear-gradient(to right, transparent 0%, transparent 15%, black 65%, black 100%)", maskImage: "linear-gradient(to right, transparent 0%, transparent 15%, black 65%, black 100%)"}}><Image src="/images/raksh-about.webp" alt="Real photograph of Raksh at an immersive venue" width={1200} height={1800} sizes="(max-width: 600px) 100vw, 60vw" style={{filter: "saturate(0.9) contrast(1.15) brightness(1.05)"}} priority /></div>
      <div className="wrap reference-hero__content">
        <span className="reference-hero__badge"><Image src="/images/raksh-close.webp" alt="" width={27} height={27} /> RAKSH JAIN / CREATOR &amp; STRATEGIST</span>
        <p className="reference-hero__script">a creator&apos;s instinct. an operator&apos;s eye.</p>
        <h1 id="hero-title">RAKSH <span>JAIN.</span></h1>
        <p className="reference-hero__description">Ideas that connect. Work that lasts. I&apos;m Raksh—a creator building content, teams and a way forward for the next generation of creators.</p>
        <div className="reference-hero__actions"><Link href="/consultations" className="reference-button">Work with me <span>↗</span></Link><Link href="/work" className="reference-underline">Explore the work <span>↗</span></Link></div>
        <div className="reference-hero__proofline" aria-label="Raksh Jain creator milestones"><span><b>1.5M+</b> YouTube audience</span><i aria-hidden="true"/><span><b>11 months</b> from 100K to 1M</span></div>
      </div>
      <VideoMarquee />
    </section>

    <section className="reference-avatar" id="meet" aria-labelledby="meet-title">
      <div className="wrap reference-avatar__copy"><p className="reference-avatar__eyebrow">The person behind Raksh Jain</p><h2 id="meet-title">Hey, I&apos;m <span>Raksh.</span></h2><p>I started with videos and questions. Today I build ideas, study what makes them work, lead a creative team, and share that experience with creators ready for their next move.</p><Link href="/about" className="reference-underline">Get to know me <span>↗</span></Link></div>
      <div className="reference-avatar__stage"><div className="reference-avatar__ring reference-avatar__ring--outer" /><div className="reference-avatar__ring reference-avatar__ring--inner" /><Image className="reference-avatar__person" src="/images/raksh-real-cutout.png" alt="Real full-length photograph of Raksh Jain" width={1080} height={1440} sizes="(max-width: 600px) 95vw, 48vw" />
        <div className="avatar-proof avatar-proof--one"><Image src="/images/raksh-close.webp" alt="" width={70} height={70} /><div><strong>Creator</strong><span><b>1.5M+</b> YouTube subscribers</span></div></div>
        <div className="avatar-proof avatar-proof--two"><Image src="/images/instagram-3m.webp" alt="" width={70} height={70} /><div><strong>Storyteller</strong><span><b>19M+</b> views on one Short</span></div></div>
        <div className="avatar-proof avatar-proof--three"><Image src="/images/raksh-stage.webp" alt="" width={70} height={70} /><div><strong>Strategist</strong><span><b>11 months</b> from 100K to 1M</span></div></div>
        <div className="avatar-proof avatar-proof--four"><Image src="/images/raksh-about.webp" alt="" width={70} height={70} /><div><strong>Operator</strong><span><b>20–25</b> people behind the work</span></div></div>
      </div>
    </section>

    <section className="reference-journey reference-section" aria-labelledby="journey-title"><div className="wrap"><p className="reference-kicker">THE JOURNEY SO FAR</p><h2 className="reference-heading" id="journey-title">Built through <em>making.</em></h2><p className="reference-section__intro">Every stage has taught me something different — about the craft, the audience,<br/>and myself. Same <strong>curiosity</strong>, a bigger canvas.</p><div className="reference-journey__grid">{journey.map((item, index) => <article className="reference-journey__card" key={item.number}><div className="reference-journey__top"><span>{item.number}</span><div className="reference-journey__line"></div><span>{item.phase}</span><div className="reference-journey__icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">{index === 0 && <path d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z"/>}{index === 1 && <><path d="M18 20V10M12 20V4M6 20v-6"/></>}{index === 2 && <><path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"/></>}</svg></div></div><h3>{item.title}</h3><p>{item.text}</p><ul>{item.list.map((line, i) => <li key={line}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">{index === 0 && i === 0 && <path d="M5 3l14 9-14 9V3z"/>}{index === 0 && i === 1 && <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20M4 19.5A2.5 2.5 0 0 0 6.5 22H20V4H6.5A2.5 2.5 0 0 0 4 6.5v13Z"/>}{index === 0 && i === 2 && <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>}{index === 1 && i === 0 && <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>}{index === 1 && i === 1 && <path d="M8 21h8M12 17v4M7 4h10M6 4v6a6 6 0 0 0 12 0V4"/>}{index === 1 && i === 2 && <path d="M9 21h6M12 17v4M9 17h6M12 2a5 5 0 0 0-3 9.58V14a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1v-2.42A5 5 0 0 0 12 2Z"/>}{index === 2 && i === 0 && <><circle cx="12" cy="12" r="10"/><path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></>}{index === 2 && i === 1 && <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 7a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM23 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>}{index === 2 && i === 2 && <path d="M22 7L13.5 15.5 8.5 10.5 2 17M16 7h6v6"/>}</svg><span>{line}</span></li>)}</ul><div className="reference-journey__bottom"><div><small>{item.metricLabel}</small><span>{item.metric}</span></div><b>↗</b></div></article>)}</div></div></section>

    <section className="reference-why reference-section" aria-labelledby="why-title"><div className="wrap"><p className="reference-kicker">WHAT I HELP WITH</p><h2 className="reference-heading" id="why-title">Better questions. <em>Clearer moves.</em></h2><div className="reference-why__grid"><div><span>01 / CLARITY</span><h3>Find your<br /><em>direction.</em></h3><p>Get clear on the creator you want to be, the audience you serve, and the ideas worth pursuing.</p></div><div><span>02 / PERFORMANCE</span><h3>Make it<br /><em>connect.</em></h3><p>Understand hooks, retention, packaging and audience response through the lens of your own content.</p></div><div><span>03 / SYSTEMS</span><h3>Build it<br /><em>to last.</em></h3><p>Create the workflows, team decisions and business structure that support the next stage.</p></div></div><div className="reference-why__bottom"><p>Strategy grounded in making the work, shaped around your stage as a creator.</p><Link href="/consultations" className="reference-underline">Find your next move <span>↗</span></Link></div></div></section>

    <section className="reference-work reference-section" id="work" aria-labelledby="work-title"><div className="wrap"><p className="reference-kicker">THE WORK SPEAKS</p><h2 className="reference-heading" id="work-title">One idea. <em>Millions watching.</em></h2><p className="reference-section__intro">A small question became a video watched more than 19 million times. The performance came from understanding the idea and the audience behind it.</p><div className="reference-work__feature"><div className="reference-work__video"><VideoEmbed id="aIoVDZAW85w" title="Can a game run on the cheapest laptop?" label="19M+ views · YouTube Short" /></div><div className="reference-work__copy"><span>FEATURED CASE STUDY / RAKSH JAIN</span><h3>Make them <em>stop.</em><br />Give them a reason <em>to stay.</em></h3><p>We took a familiar gaming curiosity and shaped it into a simple, instantly understood story. That thinking drives the work across formats and platforms.</p><Link href="/work" className="reference-button">See the work <span>↗</span></Link></div></div><div className="reference-work__stats"><div><strong>1.55M</strong><span>Subscribers in supplied Studio recording</span></div><div><strong>19.7M</strong><span>Views in supplied Short analytics</span></div><div><strong>3M+</strong><span>Views on one Instagram Reel</span></div></div></div></section>

    <section className="home-proof reference-section" aria-labelledby="home-proof-title"><div className="wrap home-proof__layout"><div className="home-proof__intro"><p className="reference-kicker">FIRST-PARTY YOUTUBE STUDIO PROOF</p><h2 id="home-proof-title">Look behind<br/><em>the numbers.</em></h2><p>Real frames from Raksh&apos;s YouTube Studio recordings: channel growth and the response to a breakout Short.</p><Link href="/work#the-proof" className="reference-underline">Explore the proof <span>↗</span></Link></div><div className="home-proof__gallery"><figure><Image src="/images/youtube-subs-proof.webp" alt="YouTube Studio channel growth recording showing 1,550,060 subscribers and a growth chart" width={1648} height={1080} sizes="(max-width: 700px) 90vw, 33vw"/><figcaption>01 / CHANNEL GROWTH</figcaption></figure><figure><Image src="/images/youtube-short-proof.webp" alt="YouTube Studio Short analytics showing 19,759,366 views and over 36,000 subscribers gained" width={980} height={836} sizes="(max-width: 700px) 90vw, 33vw"/><figcaption>02 / SHORT PERFORMANCE</figcaption></figure></div></div></section>
    <section className="reference-pricing reference-section" id="consultations" aria-labelledby="pricing-title"><div className="wrap"><p className="reference-kicker">PRIVATE 1:1 CREATOR STRATEGY</p><h2 className="reference-heading" id="pricing-title">Your stage. <em>Your next move.</em></h2><p className="reference-section__intro">Three focused ways to find direction, improve your content, or build the operation around your creator business.</p><div className="reference-pricing__grid">{modules.map((offer, index) => <article className="reference-price" key={offer.number}><div className="reference-price__top"><span>MODULE 0{index + 1}</span>{index === 1 && <b>FOR ACTIVE CREATORS</b>}</div><h3>{offer.short}</h3><p>{offer.audience}</p><strong className="reference-price__amount">{offer.price}</strong><small>{offer.days} · All taxes included</small><Link href={`/consultations#module-${offer.number}`} className="reference-button">Explore this module <span>↗</span></Link><div className="reference-price__included"><span>WHAT WE WORK THROUGH</span>{offer.topics.map((topic) => <div key={topic}>{topic}</div>)}</div></article>)}</div><p className="reference-pricing__note">Private Google Meet calls. Modules can be booked independently. Outcomes depend on implementation.</p></div></section>

    <section className="reference-brands reference-section" id="brands" aria-labelledby="brands-title"><div className="wrap"><p className="reference-kicker">BRAND COLLABORATIONS</p><h2 className="reference-heading" id="brands-title">The brand belongs <em>in the story.</em></h2><div className="reference-brands__names"><span>Samsung</span><span>Gillette</span><span>ONMO+</span><span>Triggr</span><span>Duolingo</span></div><div className="reference-brands__videos">{[brandVideos[0], brandVideos[3], brandVideos[4]].map((video) => <VideoEmbed key={video.id} id={video.id} title={video.title} label={video.brand} />)}</div><Link href="/for-brands" className="reference-underline">Explore collaborations <span>↗</span></Link></div></section>

    <section className="reference-faq reference-section" aria-labelledby="faq-title"><div className="wrap"><p className="reference-kicker">BEFORE WE WORK TOGETHER</p><h2 className="reference-heading" id="faq-title">Good questions. <em>Clear answers.</em></h2><div className="reference-faq__list">{faqs.slice(0, 5).map((faq, index) => <details key={faq.q}><summary><span>0{index + 1}</span>{faq.q}<b>+</b></summary><p>{faq.a}</p></details>)}</div><Link href="/faq" className="reference-underline">See all FAQs <span>↗</span></Link></div></section>

    <section className="reference-final" aria-labelledby="final-title"><p className="reference-kicker">THE NEXT CHAPTER</p><h2 id="final-title">Ready to make<br /><em>the next move?</em></h2><Link href="/consultations" className="reference-button">Work with Raksh <span>↗</span></Link></section>
  </>;
}
