import Image from "next/image";
import Link from "next/link";
import VideoEmbed from "../components/VideoEmbed";
import VideoMarquee from "../components/VideoMarquee";
import { brandVideos, faqs, modules } from "../lib/content";

const journey = [
  { number: "01", phase: "2022 / THE START", title: "Make the first thing.", text: "Gaming and Minecraft became the place to test ideas, learn by publishing, and understand what people actually watch.", list: ["Started RakshXD on YouTube", "Learned through real uploads", "Built a repeatable creative instinct"], metric: "START" },
  { number: "02", phase: "2024–25 / THE MOMENTUM", title: "Find the connection.", text: "One breakthrough led to a sharper process. The channel went from 100K to 1M subscribers in eleven months.", list: ["100K in November 2024", "1M in October 2025", "Multiple million-view ideas"], metric: "1M+" },
  { number: "03", phase: "NOW / THE OPERATION", title: "Build beyond the channel.", text: "Today the work spans platforms, partnerships, and a 20–25 person operation built to make consistently better content.", list: ["Broader gaming, IRL and tech", "A creative team and systems", "Creator strategy consultations"], metric: "20–25" },
];

export default function Home() {
  return <>
    <section className="reference-hero reference-hero--raksh" aria-labelledby="hero-title">
      <div className="reference-hero__portrait" data-parallax="0.025"><Image src="/images/raksh-about.webp" alt="Real photograph of Raksh at an immersive venue" width={1200} height={1800} sizes="(max-width: 600px) 100vw, 60vw" priority /></div>
      <div className="wrap reference-hero__content">
        <span className="reference-hero__badge"><Image src="/images/raksh-close.webp" alt="" width={27} height={27} /> RAKSHIT JAIN PRESENTS</span>
        <p className="reference-hero__script">a creator&apos;s instinct. an operator&apos;s eye.</p>
        <h1 id="hero-title">RAKSH<span>XD.</span></h1>
        <p className="reference-hero__description">Ideas that connect. Work that lasts. I&apos;m Raksh—a creator building content, teams and a way forward for the next generation of creators.</p>
        <div className="reference-hero__actions"><Link href="/consultations" className="reference-button">Work with me <span>↗</span></Link><Link href="/work" className="reference-underline">Explore the work <span>↗</span></Link></div>
        <div className="reference-hero__proofline" aria-label="RakshXD creator milestones"><span><b>1.5M+</b> YouTube audience</span><i aria-hidden="true"/><span><b>11 months</b> from 100K to 1M</span></div>
      </div>
      <VideoMarquee />
    </section>

    <section className="reference-avatar" id="meet" aria-labelledby="meet-title">
      <div className="wrap reference-avatar__copy"><p className="reference-avatar__eyebrow">The person behind RakshXD</p><h2 id="meet-title">Hey, I&apos;m <span>Raksh.</span></h2><p>I started with videos and questions. Today I build ideas, study what makes them work, lead a creative team, and share that experience with creators ready for their next move.</p><Link href="/about" className="reference-underline">Get to know me <span>↗</span></Link></div>
      <div className="reference-avatar__stage"><div className="reference-avatar__ring reference-avatar__ring--outer" /><div className="reference-avatar__ring reference-avatar__ring--inner" /><Image className="reference-avatar__person" src="/images/raksh-avatar-blue.webp" alt="Blue and silver illustrated portrait of Raksh" width={1154} height={1363} sizes="(max-width: 600px) 95vw, 48vw" />
        <div className="avatar-proof avatar-proof--one"><Image src="/images/raksh-close.webp" alt="" width={70} height={70} /><div><strong>Creator</strong><span><b>1.5M+</b> YouTube subscribers</span></div></div>
        <div className="avatar-proof avatar-proof--two"><Image src="/images/instagram-3m.webp" alt="" width={70} height={70} /><div><strong>Storyteller</strong><span><b>19M+</b> views on one Short</span></div></div>
        <div className="avatar-proof avatar-proof--three"><Image src="/images/raksh-stage.webp" alt="" width={70} height={70} /><div><strong>Strategist</strong><span><b>11 months</b> from 100K to 1M</span></div></div>
        <div className="avatar-proof avatar-proof--four"><Image src="/images/raksh-about.webp" alt="" width={70} height={70} /><div><strong>Operator</strong><span><b>20–25</b> people behind the work</span></div></div>
      </div>
    </section>

    <section className="reference-journey reference-section" aria-labelledby="journey-title"><div className="wrap"><p className="reference-kicker">THE JOURNEY SO FAR</p><h2 className="reference-heading" id="journey-title">Built through <em>making.</em></h2><p className="reference-section__intro">Every stage taught me a different part of the same craft: make something people care about, learn from the response, then build a better way to do it again.</p><div className="reference-journey__grid">{journey.map((item) => <article className="reference-journey__card" key={item.number}><div className="reference-journey__top"><span>{item.number}</span><span>{item.phase}</span></div><h3>{item.title}</h3><p>{item.text}</p><ul>{item.list.map((line) => <li key={line}>{line}</li>)}</ul><div className="reference-journey__bottom"><span>{item.metric}</span><b>↗</b></div></article>)}</div></div></section>

    <section className="reference-why reference-section" aria-labelledby="why-title"><div className="wrap"><p className="reference-kicker">WHAT I HELP WITH</p><h2 className="reference-heading" id="why-title">Better questions. <em>Clearer moves.</em></h2><div className="reference-why__grid"><div><span>01 / CLARITY</span><h3>Find your<br /><em>direction.</em></h3><p>Get clear on the creator you want to be, the audience you serve, and the ideas worth pursuing.</p></div><div><span>02 / PERFORMANCE</span><h3>Make it<br /><em>connect.</em></h3><p>Understand hooks, retention, packaging and audience response through the lens of your own content.</p></div><div><span>03 / SYSTEMS</span><h3>Build it<br /><em>to last.</em></h3><p>Create the workflows, team decisions and business structure that support the next stage.</p></div></div><div className="reference-why__bottom"><p>Strategy grounded in making the work, shaped around your stage as a creator.</p><Link href="/consultations" className="reference-underline">Find your next move <span>↗</span></Link></div></div></section>

    <section className="reference-work reference-section" id="work" aria-labelledby="work-title"><div className="wrap"><p className="reference-kicker">THE WORK SPEAKS</p><h2 className="reference-heading" id="work-title">One idea. <em>Millions watching.</em></h2><p className="reference-section__intro">A small question became a video watched more than 19 million times. The performance came from understanding the idea and the audience behind it.</p><div className="reference-work__feature"><div className="reference-work__video"><VideoEmbed id="aIoVDZAW85w" title="Can a game run on the cheapest laptop?" label="19M+ views · YouTube Short" /></div><div className="reference-work__copy"><span>FEATURED CASE STUDY / RAKSHXD</span><h3>Make them <em>stop.</em><br />Give them a reason <em>to stay.</em></h3><p>We took a familiar gaming curiosity and shaped it into a simple, instantly understood story. That thinking drives the work across formats and platforms.</p><Link href="/work" className="reference-button">See the work <span>↗</span></Link></div></div><div className="reference-work__stats"><div><strong>1.5M+</strong><span>YouTube subscribers</span></div><div><strong>19M+</strong><span>Views on one Short</span></div><div><strong>3M+</strong><span>Views on one Instagram Reel</span></div></div></div></section>

    <section className="reference-pricing reference-section" id="consultations" aria-labelledby="pricing-title"><div className="wrap"><p className="reference-kicker">PRIVATE 1:1 CREATOR STRATEGY</p><h2 className="reference-heading" id="pricing-title">Your stage. <em>Your next move.</em></h2><p className="reference-section__intro">Three focused ways to find direction, improve your content, or build the operation around your creator business.</p><div className="reference-pricing__grid">{modules.map((offer, index) => <article className="reference-price" key={offer.number}><div className="reference-price__top"><span>MODULE 0{index + 1}</span>{index === 1 && <b>FOR ACTIVE CREATORS</b>}</div><h3>{offer.short}</h3><p>{offer.audience}</p><strong className="reference-price__amount">{offer.price}</strong><small>{offer.days} · All taxes included</small><Link href={`/consultations#module-${offer.number}`} className="reference-button">Explore this module <span>↗</span></Link><div className="reference-price__included"><span>WHAT WE WORK THROUGH</span>{offer.topics.map((topic) => <div key={topic}>{topic}</div>)}</div></article>)}</div><p className="reference-pricing__note">Private Google Meet calls. Modules can be booked independently. Outcomes depend on implementation.</p></div></section>

    <section className="reference-brands reference-section" id="brands" aria-labelledby="brands-title"><div className="wrap"><p className="reference-kicker">BRAND COLLABORATIONS</p><h2 className="reference-heading" id="brands-title">The brand belongs <em>in the story.</em></h2><div className="reference-brands__names"><span>Samsung</span><span>Gillette</span><span>ONMO+</span><span>Triggr</span><span>Duolingo</span></div><div className="reference-brands__videos">{[brandVideos[0], brandVideos[3], brandVideos[4]].map((video) => <VideoEmbed key={video.id} id={video.id} title={video.title} label={video.brand} />)}</div><Link href="/for-brands" className="reference-underline">Explore collaborations <span>↗</span></Link></div></section>

    <section className="reference-faq reference-section" aria-labelledby="faq-title"><div className="wrap"><p className="reference-kicker">BEFORE WE WORK TOGETHER</p><h2 className="reference-heading" id="faq-title">Good questions. <em>Clear answers.</em></h2><div className="reference-faq__list">{faqs.slice(0, 5).map((faq, index) => <details key={faq.q}><summary><span>0{index + 1}</span>{faq.q}<b>+</b></summary><p>{faq.a}</p></details>)}</div><Link href="/faq" className="reference-underline">See all FAQs <span>↗</span></Link></div></section>

    <section className="reference-final" aria-labelledby="final-title"><p className="reference-kicker">THE NEXT CHAPTER</p><h2 id="final-title">Ready to make<br /><em>the next move?</em></h2><Link href="/consultations" className="reference-button">Work with Raksh <span>↗</span></Link></section>
  </>;
}
