import type { Metadata } from "next";
import Image from "next/image";
import VideoEmbed from "../../components/VideoEmbed";
import { brandVideos } from "../../lib/content";

export const metadata: Metadata = { title: "For Brands", description: "Brand collaborations with Rakshit Jain across YouTube Shorts, Instagram Reels and long-form YouTube video." };

export default function ForBrands() {
  return <><section className="page-hero brands-hero wrap"><p className="eyebrow">For brands / Rakshit Jain</p><h1 className="display-title">Make it fit the<br/><em>audience first.</em></h1><p className="lead narrow">Rakshit Jain works with brands to create content that belongs in the feed: clear concepts, strong hooks and a creator voice audiences already know.</p><a className="pill-button" href="mailto:raksh@servicemedia.in?subject=Rakshit Jain%20brand%20collaboration">Start a brand enquiry <span>↗</span></a></section>
    <section className="metric-band"><div className="wrap metric-grid"><div><strong>1.5M+</strong><span>YouTube subscribers</span></div><div><strong>350M</strong><span>total views reported by Rakshit</span></div><div><strong>Short-form</strong><span>YouTube + Instagram</span></div><div><strong>Long-form</strong><span>YouTube</span></div></div></section>
    <section className="brand-storyboard section"><div className="wrap"><div className="brand-storyboard__heading"><p className="eyebrow">The creative lens</p><h2 className="display-title">A brand moment<br/><em>people choose to watch.</em></h2><p>The product has a role in the story. The creative challenge is finding the question, format and opening that make that role feel natural to Rakshit Jain&apos;s audience.</p></div><div className="brand-storyboard__grid"><article><span>01 / AUDIENCE</span><h3>Start with what they care about.</h3><p>Gaming, technology and curiosity already shape the channel. The concept has to belong there.</p><b>↗</b></article><article className="brand-storyboard__image"><Image src="/images/raksh-night.webp" alt="Rakshit filming at night" width={900} height={1100}/><span>THE CREATOR / THE CONTEXT</span></article><article><span>02 / CONCEPT</span><h3>Give the product a job.</h3><p>A test, a challenge or a useful reveal can make the integration part of the video itself.</p><b>↗</b></article><article><span>03 / FORMAT</span><h3>Build for the platform.</h3><p>YouTube Shorts and Instagram Reels for short-form ideas. Long-form YouTube for stories that need room.</p><b>↗</b></article></div></div></section>
    <section className="section wrap"><p className="eyebrow">Past collaborations</p><div className="brand-names large"><span>Samsung</span><span>Duolingo</span><span>Gillette</span><span>ONMO+</span><span>Triggr</span></div><div className="section-heading"><div><h2 className="display-title">The brand work,<br/><em>in motion.</em></h2></div><p>Selected collaborations with concepts shaped for Rakshit Jain&apos;s audience. Turn sound on to hear the full story.</p></div><div className="brand-video-grid">{brandVideos.map((video) => <VideoEmbed key={video.id} id={video.id} title={video.title} label={video.brand}/>)}</div></section>
    <section className="section section-dark"><div className="wrap brand-editorial"><div className="brand-editorial__image"><Image src="/images/raksh-about.webp" alt="Rakshit at an event" width={900} height={1100}/></div><div><p className="eyebrow">Work together</p><h2 className="display-title">A concept with<br/><em>a reason to watch.</em></h2><p>Available formats include YouTube Shorts and Instagram Reels, plus long-form YouTube integrations or dedicated content. The strongest work begins with a concept that makes sense for the audience and the brand.</p><p>Rates, audience demographics and the latest media kit are shared on enquiry.</p><a className="underlined-link" href="mailto:raksh@servicemedia.in?subject=Rakshit Jain%20brand%20collaboration">Email raksh@servicemedia.in ↗</a><p className="small-note">Brand manager: +91 78701 25701</p></div></div></section>
  </>;
}
